# Generated by Django 3.0.5 on 2020-10-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201030_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='images'),
        ),
    ]
