# Generated by Django 3.0.5 on 2021-01-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210124_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/images/defult.jpg', null=True, upload_to='images'),
        ),
    ]
